### ISSUE TITLE
'UNLICENSED' libraries are not skipped

### ISSUE THREAD

**Issue by freeboub** [k-tomoyasu/react-native-oss-license#39]
When dependencies have a licence type UNLICENSED, it is still included in report even if --skip-not-required is provided.

According to package.json specifications, unlicensed dependencies have keyword UNLICENSED.

See: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license

**Comment by k-tomoyasu** [comment]
@freeboub Thanks for your pull request!
I have released as version `0.4.1`
